spring.application.name=ChatIntegrationZoya


spring.ai.openai.api-key=${{ secrets.GROQ}}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
